### ISSUE TITLE
Make pyMARS thread safe 

### ISSUE THREAD

**Issue by xMestas** [Niemeyer-Research-Group/pyMARS#23]

**Comment by kyleniemeyer** [comment]
Is it currently not thread safe?

**Comment by xMestas** [comment]
Yea, if you run two instances at the same time, it has issues because they are trying to write to the same hdf5 file.

**Comment by xMestas** [comment]
Yea, I was thinking of just adding the process id to the filename, creating a directory named with the process id, and storing the files in there.

**Comment by kyleniemeyer** [comment]
This should only be an issue if you are running multiple pyMARS instances in the same working directory, which is probably a bad idea with any program (and doesn't seem like it would happen much). Output files may also conflict.

If you have multiple instances running in different working directories, it isn't an issue.
