### ISSUE TITLE
BugReport

### ISSUE THREAD

**Issue by jiweiqi** [Niemeyer-Research-Group/pyMARS#32]
https://github.com/Niemeyer-Research-Group/pyMARS/blob/01a67ba2f95ad1469eeb38f7bbca1f1018153ffc/pymars/soln2ck.py#L136

`if len(equation_object.products) == 1:`

This line should be changed into `if sum(equation_object.products.values()) == 1`.

Considering the following reactions "H2O2 (+M) <=> 2 OH (+M)". There are actually two products.

**Comment by xMestas** [comment]
Thank you for the report.  Feel free to submit a pull request with your suggestion as well if you would like.

**Comment by jiweiqi** [comment]
Hi, I have submitted a pull request along with a typo fix of the doi in the ReadMe.md.

**Comment by kyleniemeyer** [comment]
This should be resolved in the recent big refactoring.
