### ISSUE TITLE
Getting Error while running pyMARS

### ISSUE THREAD

**Issue by justinjacobthomas** [Niemeyer-Research-Group/pyMARS#4]
Sir, I am using Python 2.7 and Cantera 2.3. While trying to reduce reaction mechanism, i am getting the follwing errors. (I tried both .cti file and chemkin file).
kindly help me with the same.
 Attached the screenshots.
Thanks

![pymarscti](https://user-images.githubusercontent.com/37137327/37080138-38098518-220b-11e8-989f-3f61af95a3bf.png)
![pymarsimp](https://user-images.githubusercontent.com/37137327/37080140-383966de-220b-11e8-95c1-c4a2e32353d0.png)

**Comment by kyleniemeyer** [comment]
I'm going to close this, because the package has changed significantly; please try the new version once PR #53 is merged. (Also, moving forward pyMARS only supports Python 3.6+)
