### ISSUE TITLE
Specify appropriate units for input file in documentation

### ISSUE THREAD

**Issue by jcsutherland** [Niemeyer-Research-Group/pyMARS#56]
Documentation should include units for the following elements of the input file: 
- [x] `pressure`
- [x] `temperature`
- [x] Mole/mass fractions for composition specification.  It might be nice to allow the user to specify either and convert internally
- [x] `end-time`

The sample input file should also include units in comments for clarity

**Comment by kyleniemeyer** [comment]
The docs do reference the units in this section https://niemeyer-research-group.github.io/pyMARS/usage.html#autoignition-conditions, but I agree we can list these out explicitly for more clarity (and include in the example).
