### ISSUE TITLE
Default to steady-state solutions rather than specifying `end_time`?

### ISSUE THREAD

**Issue by jcsutherland** [Niemeyer-Research-Group/pyMARS#61]
I find it a little strange that the default behavior isn't to solve the ignition problem to steady state.  Specifying `end_time` seems like something that a more advanced user may be interested in, but typically we would want a steady solution, wouldn't we?

**Comment by kyleniemeyer** [comment]
Good point. `end_time` isn't required, but the default time used internally is 10 sec, which isn't great either. 

It shouldn't be too difficult to have it integrate to steady state, although when thinking about this before I was a little concerned about it getting stuck integrating forever... not sure if I can think of when that would actually happen, though.
