### ISSUE TITLE
RuntimeError: Maximum number of steps reached before convergence for ignition case 0

### ISSUE THREAD

**Issue by shenghuiqin** [Niemeyer-Research-Group/pyMARS#66]
Hi, I was trying to reduce a big model 
```
model: 9.2blend2.cti
targets:
  - C7H10(705)
  - C7H16(37)
  - O2(2)(38)
retained-species:
  - N2(35)
method: DRGEP
error: 10.0
sensitivity-analysis: False
autoignition-conditions:
  - kind: constant volume
    pressure: 1.0
    temperature: 1000.0
    fuel:
      C7H10(705): 1.0
      C7H16(37): 1.0
    oxidizer:
      O2(2)(38): 1.0
      N2(35): 8
    equivalence-ratio: 1.0

  - kind: constant volume
    pressure: 1.0
    temperature: 1200.0
    fuel:
      C7H10(705): 1.0
      C7H16(37): 1.0
    oxidizer:
      O2(2)(38): 1.0
      N2(35): 8
    equivalence-ratio: 0.5
```
and got the Runtime error:
```
Traceback (most recent call last):
  File "/home/shenghuiqin/anaconda2/envs/spam/bin/pymars", line 12, in <module>
    sys.exit(main())
  File "/home/shenghuiqin/anaconda2/envs/spam/lib/python3.7/site-packages/pymars/__main__.py", line 10, in main
    pymars(args)
  File "/home/shenghuiqin/anaconda2/envs/spam/lib/python3.7/site-packages/pymars/pymars.py", line 319, in pymars
    path=args.path, num_threads=args.num_threads
  File "/home/shenghuiqin/anaconda2/envs/spam/lib/python3.7/site-packages/pymars/pymars.py", line 186, in main
    threshold_upper=upper_threshold, num_threads=num_threads, path=path
  File "/home/shenghuiqin/anaconda2/envs/spam/lib/python3.7/site-packages/pymars/drgep.py", line 387, in run_drgep
    model_file, ignition_conditions, phase_name=phase_name, num_threads=num_threads, path=path
  File "/home/shenghuiqin/anaconda2/envs/spam/lib/python3.7/site-packages/pymars/sampling.py", line 305, in sample
    results.append(simulation_worker(job))
  File "/home/shenghuiqin/anaconda2/envs/spam/lib/python3.7/site-packages/pymars/sampling.py", line 64, in simulation_worker
    sim.run_case(stop_at_ignition)
  File "/home/shenghuiqin/anaconda2/envs/spam/lib/python3.7/site-packages/pymars/simulation.py", line 216, in run_case
    'Maximum number of steps reached before '
RuntimeError: Maximum number of steps reached before convergence for ignition case 0
```
need help.
* also,  I don't know how to understand this,
species with the same mole fraction but different phi value?
(screenshot from pyMARS usage documentation)
https://niemeyer-research-group.github.io/pyMARS/usage.html
![image](https://user-images.githubusercontent.com/44587695/64368373-2d3f5b80-cfe8-11e9-958f-ead6a4648704.png)
* another question is when creating a YAML file, how many auto-ignition conditions are appropriate? 
the example file uses two (1atm phi=1 and 1000K; 1atm phi=0.5 and 1200K)(see screenshot above),
I want to use the reduced model to simulate the corresponding exp condition of T range from 650 -1500K, P range from 10--40 bar. How to distribute autoignition-conditions? will keep P constant, every 100K do a simulation from 650 make sense?

**Comment by xMestas** [comment]
Hello,

- It looks like your run time error occurs because your model did not ignite under the first set of initial conditions in the auto-ignition simulation in the given number of steps.  Maybe the error message could be easier to understand.

- The equivalence ratio and mole fractions given are passed to the set_equivalence_ratio function from Cantera [here](https://github.com/Niemeyer-Research-Group/pyMARS/blob/master/pymars/simulation.py#L64).  See the documentation [here](https://cantera.org/documentation/docs-2.4/sphinx/html/cython/thermo.html).

- You can certainly set up your initial conditions like this!  Every 100K sounds like a reasonable step in temperature.  The trade-offs you need to consider are more initial conditions mean that the reduction will take longer and will be less effective, but the benefit is that the error in the reduced model will be consistent across a wider variety of conditions.

**Comment by kyleniemeyer** [comment]
@shenghuiqin to clarify about the mole fraction/equivalence ratio, the values in the `fuel` and `oxidizer` fields are the mole fractions in the fuel/oxidizer mixture. (So, in the example given, the oxidizer is the typical representation for air of 1.0 O2 + 3.76 N2.) Then, as @xMestas mentioned, the equivalence ratio specified will be used to find the appropriate ratio of fuel and oxidizer.

Alternatively, you can leave out `equivalence-ratio`, `fuel`, and `oxidizer` and specify the molar amounts of each reactant:
```yaml
reactants:
  CH4: 1.0
  O2: 2.0
  N2: 7.52
```

**Comment by shenghuiqin** [comment]
thank you both!

I changed the simulation condition which I can get IDT using cantera,
```
model: 9.2blend2.cti
targets:
  - C7H10(705)
  - C7H16(37)
  - O2(2)(38)
retained-species:
  - N2(35)
method: DRGEP
error: 10.0
sensitivity-analysis: False
autoignition-conditions:
  - kind: constant volume
    pressure: 20.0
    temperature: 800.0
    reactants:
      C7H10(705): 1
      C7H16(37): 1
      O2(2)(38): 21
      N2(35): 60
```
but on pyMARS I still get the RuntimeError, I tried on several T and P, still did not work.
what else could be the reason to have this error?

**Comment by kyleniemeyer** [comment]
@shenghuiqin is the ignition delay time you got with Cantera quite long? It may be that the low temperature and extremely lean mixture takes too long to ignite for the default pyMARS parameters. 

As mentioned in the [Usage docs](https://niemeyer-research-group.github.io/pyMARS/usage.html), you can override these defaults with either a maximum integration time (using an `end-time:` field) or a larger number of steps (`max-steps:`, beyond the default of 10000). This would be needed for each autoignition condition with this issue.

**Comment by shenghuiqin** [comment]
yeah, really loong on cantera, that's why I want to reduce it.
thank you, I will try that again

**Comment by shenghuiqin** [comment]
It works! setting   ```max-steps: 18000```

**Comment by AH9316** [comment]
Hi, @shenghuiqin. I am also reducing a big mechanism right now and I meet the same situation as you. Where did you put max-steps? We should specify the max-steps at each of -kind block or we can set it at the beginning of the input file? Thank you!

**Comment by shenghuiqin** [comment]
> Hi, @shenghuiqin. I am also reducing a big mechanism right now and I meet the same situation as you. Where did you put max-steps? We should specify the max-steps at each of -kind block or we can set it at the beginning of the input file? Thank you!
hi, AH. Attached is my reduction_input.yaml file, at bottom of each kind set, you can specify max-steps.
hope this helps.
```
model: 9.22blend4_toluene.cti
targets:
  - Toluene(1)
  - C7H16(37)
  - O2(2)(38)
retained-species:
  - N2(35)
method: DRGEP
error: 10.0
sensitivity-analysis: False
autoignition-conditions:
  - kind: constant volume
    pressure: 20.0
    temperature: 700.0
    reactants:
      C7H10(705): 1
      C7H16(37): 1
      O2(2)(38): 21
    max-steps: 25000

  - kind: constant volume
    pressure: 20.0
    temperature: 800.0
    reactants:
      C7H10(705): 1
      C7H16(37): 1
      O2(2)(38): 21
    max-steps: 25000


  - kind: constant volume
    pressure: 20.0
    temperature: 900.0
    reactants:
      C7H10(705): 1
      C7H16(37): 1
      O2(2)(38): 21
    max-steps: 25000

```

**Comment by AH9316** [comment]
Thank you so much!! @shenghuiqin

**Comment by shenghuiqin** [comment]
@AH9316
