### ISSUE TITLE
pyMARs documentation for newbies

### ISSUE THREAD

**Issue by gdeekshita03** [Niemeyer-Research-Group/pyMARS#83]
Hi! So I am working on developing a pymars documentation for beginners who are unfamiliar with this platform and are new to model reduction in general. I currently have the documentation developed for this and was wondering where I can go from here. For instance, what platform would be best to publish this on?

**Comment by wandadars** [comment]
I've transitioned documentation for software that I am working on over to a Sphinx/readthedocs style and it's great. That would probably be one of the best ways to integrate documentation into the project/ Plus, it is free if the repository is public.

**Comment by kyleniemeyer** [comment]
Hi folks, thanks for your interest. pyMARS does have documentation available: https://niemeyer-research-group.github.io/pyMARS/ (this is linked to from the main repo page).

**Comment by xyt0808** [comment]
Hello friends, I'm interested in pyMARS and want to learn the simplification of chemical reaction mechanisms, but I don't know how to use it, can you guys help me? Is it possible to communicate and learn by email?

**Comment by kyleniemeyer** [comment]
@xyt0808 I recommend starting with the examples given in the documentation: https://niemeyer-research-group.github.io/pyMARS/usage.html#example-reduction

However, please note that pyMARS is currently a bit out of date, using an older version of Cantera.
