### ISSUE TITLE
Does it still work with cantera 3.0

### ISSUE THREAD

**Issue by jerome-braun** [Niemeyer-Research-Group/pyMARS#85]
Hey everyone.
Recently, I began my bachelor's thesis in mechanical engineering with the goal of reducing the chemical reaction mechanism for a specific problem. Over the past few days, I've been attempting to understand your code. However, I encountered some issues when trying to execute it. Unfortunately, I couldn't find any information regarding the version of Cantera needed to run the code. I am currently using Cantera 3.0 and Python 3.9.13. Is it still compatible with Cantera 3.0?

Some of the errors I encountered include:

 File "build\\python\\cantera\\solutionbase.pyx", line 180, in cantera.solutionbase._SolutionBase._init_yaml
cantera._utils.CanteraError:
*******************************************************************************
CanteraError thrown by newSolution:
The CTI and XML formats are no longer supported.
*******************************************************************************

 File "C:\Users\braun\miniconda3\envs\PYMARS\lib\site-packages\pymars\pymars.py", line 310, in pymars
    inputs.model = convert(inputs.model, args.thermo, args.transport, args.path)
AttributeError: can't set attribute

Kind regards

Jerome

**Comment by wandadars** [comment]
Does the pyMARS code use only the CTI or XML file format for mechanisms?  Cantera solely uses YAML now, so you'd have to pass your mechanism through the cti2yaml  tool or just re-generate them from a Chemkin input if that's the only issue.

**Comment by kyleniemeyer** [comment]
pyMARS has unfortunately not yet been updated to work with Cantera 3.0, though there is an open PR for this. In the meantime, I would recommend creating a virtual environment (using pip or conda, for example) with the older Cantera version for using pyMARS.

**Comment by jerome-braun** [comment]
> pyMARS has unfortunately not yet been updated to work with Cantera 3.0, though there is an open PR for this. In the meantime, I would recommend creating a virtual environment (using pip or conda, for example) with the older Cantera version for using pyMARS.

Thanks a lot for the quick response I will give it a try with an older version
